[build]
  publish = "/"
  functions = "functions"
  command = "npm install"

# Add the Netlify Functions Install Core plugin
[[plugins]]
  package = "@netlify/plugin-functions-install-core"

# Handle form submissions
[build.processing.html]
  pretty_urls = true
