[build]
  publish = "/"
  functions = "functions"
  command = "npm install"

# Add the Netlify Functions Install Core plugin
[[plugins]]
  package = "@netlify/plugin-functions-install-core"

# Handle form submissions
# REMOVED pretty_urls setting
# [build.processing.html]
#  pretty_urls = true
